package TestNG;
//Generated by Selenium IDE

//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class IDE1 {

	public WebDriver driver;
	JavascriptExecutor js;

	@BeforeTest
	public void setUp() {
		
		driver = new FirefoxDriver();
		//System.setProperty("webdriver.chrome.driver", "E:\\Selenium\\chromedriver.exe");
		System.setProperty("webdriver.gecko.driver", "D:\\Automation testing_doc\\geckodriver-v0.24.0-win64\\geckodriver.exe");
		js = (JavascriptExecutor) driver;
		new HashMap<String, Object>();
		
	}

	@AfterTest
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void tC3() {
		driver.get("https://gicchannel.gic.vn/");
		//driver.manage().window().setSize(new Dimension(1382, 744));
		driver.manage().window().maximize();
		
		driver.findElement(By.name("USER_LOGIN")).sendKeys("YouNetSI_test20");
		
		driver.findElement(By.name("USER_PASSWORD")).sendKeys("qưerty123");
		driver.findElement(By.cssSelector(".login-btn")).click();
		
		driver.findElement(By.id("feed-add-post-form-link-text")).click();
		driver.findElement(By.cssSelector(".feed-add-post-form-lists > .menu-popup-item-text")).click();
		driver.findElement(By.cssSelector(".feed-add-post-form-listsfeed-add-post-form-lists-item:nth-child(4) > .menu-popup-item-text")).click();
		js.executeScript("window.scrollTo(0,0)");
		driver.findElement(By.name("PROPERTY_123")).click();
		{
			WebElement dropdown = driver.findElement(By.name("PROPERTY_123"));
			dropdown.findElement(By.xpath("//option[. = 'Tái tục']")).click();
		}
		driver.findElement(By.cssSelector("tr:nth-child(2) > td > .bx-bp-select option:nth-child(2)")).click();
		driver.findElement(By.name("PROPERTY_124")).click();
		{
			WebElement dropdown = driver.findElement(By.name("PROPERTY_124"));
			dropdown.findElement(By.xpath("//option[. = 'Xe lẻ']")).click();
		}
		driver.findElement(By.cssSelector("tr:nth-child(3) .bx-bp-select option:nth-child(2)")).click();
		
		driver.findElement(By.name("PROPERTY_125[n0][VALUE]")).sendKeys("aaaaaaaaaaaaaa");
		driver.findElement(By.name("PROPERTY_126")).click();
		{
			WebElement dropdown = driver.findElement(By.name("PROPERTY_126"));
			dropdown.findElement(By.xpath("//option[. = 'Qua đại lý']")).click();
		}
		driver.findElement(By.cssSelector("tr:nth-child(5) .bx-bp-select option:nth-child(3)")).click();
		
		driver.findElement(By.name("PROPERTY_127[n0][VALUE]")).sendKeys("aaaaaaaaaaaaa");
		
		driver.findElement(By.name("PROPERTY_128[n0][VALUE]")).sendKeys("aaaaaaaaaaaaa");
		
		driver.findElement(By.name("PROPERTY_129[n0][VALUE]")).sendKeys("50");
		
		driver.findElement(By.name("PROPERTY_130[n0][VALUE]")).sendKeys("aaaaaaaa");
		driver.findElement(By.name("PROPERTY_131")).click();
		{
			WebElement dropdown = driver.findElement(By.name("PROPERTY_131"));
			dropdown.findElement(By.xpath("//option[. = 'Xe tải']")).click();
		}
		driver.findElement(By.cssSelector("tr:nth-child(10) option:nth-child(3)")).click();
		
		driver.findElement(By.name("PROPERTY_132[n0][VALUE]")).sendKeys("aaaaaaaaaaaa");
		
		driver.findElement(By.name("PROPERTY_133[n0][VALUE]")).sendKeys("aaaaaaaaaaaaa");
		driver.switchTo().frame(1);
		driver.findElement(By.cssSelector("body")).click();
		{
			WebElement element = driver.findElement(By.cssSelector("body"));
			js.executeScript(
					"if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'aaaaaaaaaaaaaaa<br>'}",
					element);
		}
		driver.switchTo().defaultContent();
		
		driver.findElement(By.name("PROPERTY_135[n0][VALUE]")).sendKeys("111111");
		
		driver.findElement(By.id("input-phyqg3")).sendKeys("11.111");
		driver.findElement(By.id("selector-phyqg3")).click();
		{
			WebElement dropdown = driver.findElement(By.id("selector-phyqg3"));
			dropdown.findElement(By.xpath("//option[. = 'US Dollar']")).click();
		}
		driver.findElement(By.cssSelector("#selector-phyqg3 > option:nth-child(1)")).click();
		
		driver.findElement(By.id("input-jx1un7")).sendKeys("2.222.222.222");
		driver.findElement(By.id("selector-jx1un7")).click();
		{
			WebElement dropdown = driver.findElement(By.id("selector-jx1un7"));
			dropdown.findElement(By.xpath("//option[. = 'Euro']")).click();
		}
		driver.findElement(By.cssSelector("#selector-jx1un7 > option:nth-child(3)")).click();
		
		driver.findElement(By.name("PROPERTY_138[n0][VALUE]")).sendKeys("aaaaaaaaaaa");
		driver.findElement(By.name("PROPERTY_139")).click();
		{
			WebElement dropdown = driver.findElement(By.name("PROPERTY_139"));
			dropdown.findElement(By.xpath("//option[. = 'Bảo hiểm TNDS Tự nguyện']")).click();
		}
		driver.findElement(By.cssSelector("tr:nth-child(18) option:nth-child(3)")).click();
	
		driver.findElement(By.id("input-ubd0le")).sendKeys("1.111.111");
		driver.findElement(By.id("selector-ubd0le")).click();
		driver.findElement(By.cssSelector("#selector-ubd0le > option:nth-child(2)")).click();
		
		driver.findElement(By.id("input-drh6vm")).sendKeys("1.111.111.111");
		driver.findElement(By.id("selector-drh6vm")).click();
		{
			WebElement dropdown = driver.findElement(By.id("selector-drh6vm"));
			dropdown.findElement(By.xpath("//option[. = 'Euro']")).click();
		}
		driver.findElement(By.cssSelector("#selector-drh6vm > option:nth-child(3)")).click();
		
		driver.findElement(By.name("PROPERTY_142[n0][VALUE]")).sendKeys("51");
		driver.findElement(By.cssSelector("tr:nth-child(21) > td:nth-child(2)")).click();
		
		driver.findElement(By.name("PROPERTY_143[n0][VALUE]")).sendKeys("aaaaaaaa");
		driver.findElement(By.name("PROPERTY_144[n0][VALUE]")).click();
		driver.findElement(By.id("YNSI_blog-submit-button-save")).click();
		driver.findElement(By.cssSelector("#\38ZtrP8AoZ7_wf_status > .bp-status-inner > span")).click();
		driver.findElement(By.cssSelector(".bx-im-informer-icon")).click();
		driver.findElement(By.linkText("Kiểm tra thông tin nhập - QT miễn giảm xe cơ giới")).click();
		driver.findElement(By.cssSelector("#bx_left_menu_menu_live_feed .menu-item-link-text")).click();
		{
			WebElement element = driver.findElement(By.id("user-name"));
			
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		driver.findElement(By.id("user-name")).click();
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		driver.findElement(By.cssSelector(".menu-popup-item:nth-child(5) > .menu-popup-item-text")).click();
		driver.findElement(By.name("USER_LOGIN")).click();
		driver.findElement(By.name("USER_LOGIN")).sendKeys("YouNetSI_testhead");
		driver.findElement(By.name("USER_PASSWORD")).click();
		driver.findElement(By.name("USER_PASSWORD")).sendKeys("qưerty123");
		driver.findElement(By.cssSelector(".login-btn")).click();
		driver.findElement(By.cssSelector(".bx-im-informer-icon")).click();
		driver.findElement(By.cssSelector(".bx-notifier-item-223 .bx-notifier-item-text")).click();
		driver.findElement(By.linkText("Close")).click();
		driver.findElement(By.id("sonet_log_day_item_lsV5Fpel")).click();
		{
			WebElement element = driver.findElement(By.linkText("QT giảm phí xe cơ giới"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		driver.findElement(By.cssSelector("#\38ZtrP8AoZ7_task_buttons_190 .bp-button")).click();
		driver.findElement(By.name("task_comment")).click();
		driver.findElement(By.name("task_comment")).sendKeys("tuchoi");
		driver.findElement(By.cssSelector(".bp-button-decline")).click();
		driver.findElement(By.id("sonet_log_day_item_lsV5Fpel")).click();
		driver.findElement(By.cssSelector("#sonet_log_day_item_lsV5Fpel .feed-post-item")).click();
		{
			WebElement element = driver.findElement(By.linkText("QT giảm phí xe cơ giới"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		driver.findElement(By.id("user-name")).click();
		driver.findElement(By.cssSelector(".menu-popup-item:nth-child(5) > .menu-popup-item-text")).click();
		
		driver.findElement(By.name("USER_LOGIN")).sendKeys("YouNetSI_test20");
		
		driver.findElement(By.name("USER_PASSWORD")).sendKeys("qưerty123");
		driver.findElement(By.cssSelector(".login-btn")).click();
		driver.findElement(By.cssSelector(".bx-im-informer-icon")).click();
		driver.findElement(By.cssSelector(".bx-notifier-item-224 .bx-notifier-item-text")).click();
		driver.findElement(By.linkText("Close")).click();
	}
}




